accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<int:pk>/update', views.update, name='update'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/comment/', views.comment, name='comment' ),
    path('profile/<int:pk>', views.profile, name='profile'),
]

gstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    profile_picture = ProcessedImageField(
        blank=True,
        upload_to='profile/', 
        processors=[Thumbnail(200, 200)],
        format='JPEG',
        options={'quality': 60},
        default='../static/accounts/default_profile.jpg'
    )

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    book_users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Bookmark', related_name='book_articles', blank=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Picture(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    upload_picture = ProcessedImageField(
        blank=True,
        upload_to='article_pictures/', 
        processors=[Thumbnail(500, 500)],
        format='JPEG',
        options={'quality': 60},
    )


class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as SuperUserCreationForm
from django.contrib.auth.forms import UserChangeForm as SuperUserChangeForm


class UserCreationForm(SuperUserCreationForm):

    class Meta(SuperUserCreationForm.Meta):
        model = get_user_model()
        fields = SuperUserCreationForm.Meta.fields


class UserChangeForm(SuperUserChangeForm):

    class Meta(SuperUserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'profile_picture',)

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    picture = forms.ImageField()
    class Meta:
        model = Article
        fields = ('content', 'picture',)


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', )
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserCreationForm, UserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm(request)
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('articles:index')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def update(request, pk):
    if request.method == 'POST':
        form = UserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = UserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from .forms import ArticleForm, CommentForm
from .models import Article, Picture, Comment


def index(request):
    if request.user.is_authenticated:
        articles = Article.objects.all()[::-1]
        comment_form = CommentForm()
        context = {
            'articles': articles,
            'comment_form':comment_form,
        }
        return render(request, 'articles/index.html', context)
    else:
        return redirect('accounts:login')


def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article = form.save()
            picture = Picture()
            picture.article = article
            picture.upload_picture = form.cleaned_data.get('picture')
            picture.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)


def profile(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    context = {
        'user': user,
    }
    return render(request, 'articles/profile.html', context)


def comment(request, pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            article = get_object_or_404(Article, pk=pk)
            comment.article = article
            comment.save()
            return redirect('articles:index')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container d-flex flex-row justify-content-center" style="max-width:975px;">
  <div class="row">
    <h1 class="text-center">로그인</h1>
    <hr>
    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit">
    </form>
    <hr>
    <a href="">회원가입</a>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container d-flex flex-row justify-content-center" style="max-width:975px;">
  <div class="row">
    <h1 class="text-center">회원가입</h1>
    <hr>
    <form action="{% url 'accounts:signup' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit">
    </form>
    <hr>
    <a href="{% url 'accounts:login' %}">로그인</a>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container d-flex flex-row justify-content-center" style="max-width:975px;">
  <div class="row">
    <h1 class="text-center">프로필 편집</h1>
    <hr>
    <form action="{% url 'accounts:update' request.user.pk %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit">
    </form>
  </div>
</div>
{% endblock content %}

articles/templates/articles/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="container d-flex flex-row justify-content-center" style="max-width:975px;">
  <div class="row">
    <h3 class="text-center">새 게시물 만들기</h3>
    <hr>
    <form action="{% url 'articles:create' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
    </form>
  </div>
</div>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container d-flex flex-row justify-content-center justify-content-lg-start" style="max-width:975px;">
  <div class="d-flex">
    {% for picture in article.picture_set.all %}
      <img src="{{ picture.upload_picture.url }}" alt="">
    {% endfor %}
  </div>
  <section>
    <p>{{ article.user }}</p>
    <hr>
    <p>{{ article.content }}</p>
    <hr>
    {% for comment in article.comment_set.all %}
      <p>{{ comment.user }} {{ comment.content }}</p>
    {% endfor %}
  </section>
</div>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'articles/index.css' %}">
<div class="container d-flex flex-row justify-content-center justify-content-lg-start" style="max-width:975px;">
  <div class="row">
    <div class="" style="height:1000px; width:650px;">
      {% for article in articles %}
        <article class="border border-1 my-2">
          <a href="{% url 'articles:profile' article.user.pk %}" class="title d-flex align-center my-3">
            <div class="article-profile mx-3">
              <img src="{{ article.user.profile_picture.url }}" alt="" class="img-fluid rounded-circle">
            </div>
            <p class="mt-1 mb-0">{{ article.user }} ({{ article.pk }}번글) </p>
          </a>
          {% for picture in article.picture_set.all %}
            <img src="{{ picture.upload_picture.url }}" alt="" style="width: 100%">
          {% endfor %}
          <div class="content mx-3">
            <p class="mt-3">{{ article.content }}</p>
            <a href="{% url 'articles:detail' article.pk %}" class="">댓글 {{ article.comment_set.all.count }}개</a>
            {% for comment in article.comment_set.all %}
              <p>{{ comment.user }} {{ comment.content }}</p>
            {% endfor %}
          </div>
          <form action="{% url 'articles:comment' article.pk %}" method="POST" class="border-top py-2 d-flex justify-content-between">
            {% csrf_token %}
            <div>
              <i class="fa-regular fa-face-smile fa-xl mx-3"></i>
              {{ comment_form }}
            </div>
            <input type="submit" value="게시" class="mx-3">
          </form>
        </article>
      {% endfor %}
    </div>
  </div>
  <div class="d-none d-lg-block position-fixed d-flex flex-column" style="height:200px; width:325px; left:50%; transform: translate(163px, 0);">
    <div class="d-flex mt-5 mx-3">
      <div style="height: 56px; width: 56px;">
        <img src="{{ request.user.profile_picture.url }}" alt="" class="img-fluid  rounded-circle">
      </div>
      <div class="m-1 mx-3 mb-3">
        <p class="m-0">{{ request.user.username }}</p>
        <p class="m-0 name">{{ request.user.first_name }}</p>
      </div>
    </div>
    <div class="mx-3">
      <p>회원님을 위한 추천</p>
    </div>
  </div>
</div>
{% endblock content %}

articles/templates/articles/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container d-flex flex-row justify-content-center justify-content-lg-start" style="max-width:975px;">
  <header class="d-flex">
    <div class="" style="height: 150px; width: 150px; margin: 100px; margin-top: 50px;">
      <img src="{% static 'accounts/default_profile.jpg' %}" alt="" class="img-fluid rounded-circle">
    </div>
    <div style="margin-top: 50px;">
      <p>
        {{ user.username }}
        <a href="{% url 'accounts:update' user.pk %}"><button>프로필 편집</button></a>
      </p>
      <p>{{ user.first_name }}</p>
      <p>{{ user.last_name }}</p>
    </div>
  </header>
  <article>

  </article>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Gstagram</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container" style="justify-content: space-between; flex-wrap:nowrap; min-width:650px; max-width:975px;">
      <a class="navbar-brand" href="{% url 'articles:index' %}"><img style="width: 100px" src="https://www.instagram.com/static/images/web/mobile_nav_type_logo.png/735145cfe0a4.png" alt="img"></a>
      <input class="form-control me-2" style="width:300px" type="search" placeholder="검색하지마" aria-label="Search">
      <div class="d-flex align-center">
        <a href="{% url 'articles:index' %}" class="fa-solid fa-house fa-xl text-black text-decoration-none mx-2 mt-3"></a>
        <a href="{% url 'articles:create' %}" class="fa-regular fa-square-plus fa-xl text-black text-decoration-none mx-2 mt-3"></a>
        <a href="" class="fa-regular fa-heart text-black fa-xl text-decoration-none mx-2 mt-3"></a>
        {% if request.user.is_authenticated %}
          <div class="dropdown">
            <img src="{{ request.user.profile_picture.url }}" alt="profile" style="width: 25px;" class="rounded-circle dropdown-toggle mx-2" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li><a class="dropdown-item" href="{% url 'articles:profile' request.user.pk %}">프로필</a></li>
              <li><a class="dropdown-item" href="#">북마크</a></li>
              <hr>
              <li>
                <form action="{% url 'accounts:logout' %}" method="POST" class="dropdown-item">
                  {% csrf_token %}
                  <label for="logout">로그아웃</label>
                  <input type="submit" value="로그아웃" id="logout" class="d-none">
                </form>
              </li>
            </ul>
          </div>
        {% else %}
          <a href="{% url 'accounts:login' %}" class="mx-2"><img src="{% static 'accounts/default_profile.jpg' %}" alt="profile" style="width: 25px;" class="rounded-circle"></a>        
        {% endif %}
      </div>
    </div>
  </nav>
  {% block content %}{% endblock content %}
  <script src="https://kit.fontawesome.com/5baadafa4b.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>